CHARTS = \
	{{{filename}}}.png

MERMAID = ~/node_modules/.bin/mmdc

all: $(CHARTS)
	mkdir -p products
	cp *.png products
	@echo done

%.png: %.mmd
	@echo compiling $<...
	$(MERMAID) -i "$(basename $<).mmd" -o $(basename $<).png
